# Generated by Django 2.0.7 on 2018-08-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='desciption',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
