# Generated by Django 2.0.7 on 2018-08-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_poll_desciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='desciption',
            new_name='explination',
        ),
    ]
