# Generated by Django 2.0.7 on 2018-08-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20180809_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollitem',
            name='image_url',
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
