# Generated by Django 2.0.7 on 2018-08-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180814_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_logo',
            field=models.ImageField(blank=True, height_field=600, upload_to='', width_field=600),
        ),
    ]
