# Generated by Django 2.0.3 on 2018-08-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_votehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votehistory',
            name='PollItem',
        ),
        migrations.DeleteModel(
            name='VoteHistory',
        ),
    ]
