# Generated by Django 2.0.3 on 2018-08-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20180828_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollitem', models.CharField(max_length=200)),
                ('voter', models.CharField(max_length=200)),
                ('vote_time', models.DateField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Poll')),
            ],
        ),
    ]
